image: hiroyukionaka/pandoc-redpen-ja

pipelines:
  default:
      - step:
          script:
            - rm -rf target
            - mkdir -p target
            - curl -L -O http://sakura.fieldnotes.jp/images/f2.ttf
            - curl -L -O http://sakura.fieldnotes.jp/images/b2.ttf
            - curl -L -O http://sakura.fieldnotes.jp/images/RictyDiminished-Regular.ttf
            - bash ./build.sh
            - bash ./deploy.sh master
  branches:
    release:
      - step:
          script:
            - rm -rf target
            - mkdir -p target
            - curl -L -O http://sakura.fieldnotes.jp/images/f2.ttf
            - curl -L -O http://sakura.fieldnotes.jp/images/b2.ttf
            - curl -L -O http://sakura.fieldnotes.jp/images/RictyDiminished-Regular.ttf
            - bash ./build.sh
            - bash ./deploy.sh release 
